---
title: "Project_Kamat_Aneesh"
author: "Aneesh Kamat"
date: "24/07/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
list.of.packages <- c("fpp2", "dplyr", "GGally", "gridExtra", "tibbletime", "lubridate", "xts", "forecast", "tseries", "urca", "reshape2")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(fpp2)
library(dplyr)
library(GGally)
library(gridExtra)
library(tibbletime)
library(lubridate)
library(xts)
library(forecast)
library(tseries)
library(urca)
library(reshape2)

```

```{r}
main_db <- read.csv("all_currencies.csv", header = T)

str(main_db)
levels(main_db$Symbol)

```

```{r}
btc_data <- main_db[main_db$Symbol == 'BTC',]
btc_data$Date <- as.Date(btc_data$Date)
str(btc_data)

```

```{r}
main_db_mc <-  main_db[main_db$Date == last(main_db$Date),c(2,3,9)]
main_db_mc <-
  main_db_mc %>%
  arrange(desc(Market.Cap)) %>%
  head(10)

#options(scipen = 999)
ggplot(main_db_mc, aes(x=reorder(Symbol, Market.Cap), y=Market.Cap/1000000000)) +
  geom_col(aes(fill=Symbol)) +
  coord_flip() +
  scale_fill_brewer(palette = "Paired") +
  labs(x = "Cryptocurrency", y = "Market Cap (In Billons USD)", 
       title = "Top 10 Cryptocurrencies by Market Cap",fill = "Cryptocurrency")

```

```{r}
main_db_v <-  main_db[main_db$Date == last(main_db$Date),c(2,3,8)]
main_db_v <-
  main_db_v %>%
  arrange(desc(Volume)) %>%
  head(10)

ggplot(main_db_v, aes(x=reorder(Symbol, Volume), y=Volume/1000000000)) +
  geom_col(aes(fill=Symbol)) +
  coord_flip() +
  scale_fill_brewer(palette = "Paired") +
  labs(x = "Cryptocurrency", y = "Transaction Volume in Million (In Millions)", 
       title = "Top 10 Cryptocurrencies by Transaction Volume",fill = "Cryptocurrency")

```

```{r}
topcurrencies <-
  main_db_mc %>%
  arrange(desc(Market.Cap)) %>%
  head(5) %>%
  select(Symbol)

topcurrencies <- topcurrencies$Symbol

tc_subset <- 
  main_db %>%
  filter(Symbol %in% topcurrencies) %>%
  select(Date, Symbol, Close)
tc_subset$Date <- as.Date(tc_subset$Date, format = "%Y-%m-%d")

ggplot(tc_subset, aes(Date, Close)) +
  geom_line(aes(color=Symbol, group=Symbol)) +
  labs(x = "Year", y = "Price per unit (In USD)", 
       title = "Price per unit of currency",color = "Cryptocurrency")

```

```{r}
tc_subset_2017 <- tc_subset[tc_subset$Date > '2016-12-31',]
ggplot(tc_subset_2017, aes(Date, Close)) +
  geom_line(aes(color=Symbol, group=Symbol)) +
  labs(x = "Year", y = "Price per unit (In USD)", 
       title = "Price per unit of currency (Post 2017)",color = "Cryptocurrency") +
  scale_x_date(date_labels= "%b %Y", date_breaks = "2 months")

```

```{r}
btc_ts=ts(btc_data$Close,frequency=365,start=c(2013,4,28))
autoplot(btc_ts) + labs(y = "Price", title = "Time Series for Bitcoin")

```

```{r}
btc_daily <- as_tbl_time(btc_data, index = Date)
btc_daily <- as_period(btc_daily, 'd')
btc_daily <- ts(btc_daily$Close, frequency = 365, start=c(2013,4,28))
autoplot(btc_daily) + labs(y="Price", title = "Bitcoin Price (Daily)")

```

```{r}
btc_mthly <- as_tbl_time(btc_data, index = Date)
btc_mthly <- as_period(btc_mthly, 'm')
btc_mthly <- ts(btc_mthly$Close, frequency = 12, start=c(2013,4))
autoplot(btc_mthly) + labs(y="Price", title = "Bitcoin Price (Monthly)")

```

```{r}
# Naive 
btc_train <- subset(btc_mthly, end = 53)
btc_test <- subset(btc_mthly, start = 54)

btc_naive <- naive(btc_train, h = 13)
autoplot(btc_naive) + labs(y="Price")

accuracy(btc_naive, btc_test)

autoplot(btc_naive) +
  autolayer(fitted(btc_naive), series="Fitted") + labs(y="Price")

```

```{r}
### Seasonal Naive

btc_snaive <- snaive(btc_train, h = 13)

autoplot(btc_snaive) + labs(y="Price")

accuracy(btc_snaive, btc_test)

autoplot(btc_snaive) +
  autolayer(fitted(btc_snaive), series="Fitted") + labs(y="Price")

```

```{r}
### SES
## Monthly

ses.btc <- ses(btc_train, h = 13)
autoplot(ses.btc) + labs(y = "Price")

btc.diff <- diff(btc_train)
autoplot(btc.diff) + labs(y = "Price (Differenced)", title = "Differenced Series")

ses.btc.diff <- ses(btc.diff, h = 13) 
autoplot(ses.btc.diff) + labs(y = "Price (Differenced)")

ses.btc.test <- diff(btc_test)

accuracy(ses.btc.diff, ses.btc.test)

alpha <- seq(.01, .99, by = .01)
RMSE <- NA
for(i in seq_along(alpha)) {
  fit <- ses(btc.diff, alpha = alpha[i], h = 13)
  RMSE[i] <- accuracy(fit, ses.btc.test)[2,2]
}

# convert to a data frame and idenitify min alpha value
alpha.fit <- data_frame(alpha, RMSE)
alpha.min <- filter(alpha.fit, RMSE == min(RMSE))

# plot RMSE vs. alpha
ggplot(alpha.fit, aes(alpha, RMSE)) +
  geom_line() +
  geom_point(data = alpha.min, aes(alpha, RMSE), size = 2, color = "blue") +
  labs(title = "RMSE vs Alpha")

ses.btc.opt <- ses(btc.diff, alpha = .13, h = 13)

accuracy(ses.btc.opt, ses.btc.test)

autoplot(ses.btc.opt) +
  theme(legend.position = "bottom") + labs(y = "Price (Differenced)")

autoplot(ses.btc.test) +
  autolayer(ses.btc.opt, alpha = .5) +
  ggtitle("Predicted vs. actuals for the test data set") + 
  labs(y = "Price (Differenced)")

```

```{r}
## Daily
btc_train <- subset(btc_daily, end = 1780)
btc_test <- subset(btc_daily, start = 1781)

ses.btc <- ses(btc_train, h = 199)
autoplot(ses.btc) + labs(y = "Price")

btc.diff <- diff(btc_train)
autoplot(btc.diff) + labs(y = "Price (Differenced)", title = "Differenced Series")

ses.btc.diff <- ses(btc.diff, h = 199) 
autoplot(ses.btc.diff) + labs(y = "Price (Differenced)")

ses.btc.test <- diff(btc_test)

accuracy(ses.btc.diff, ses.btc.test)

alpha <- seq(.01, .99, by = .01)
RMSE <- NA
for(i in seq_along(alpha)) {
  fit <- ses(btc.diff, alpha = alpha[i], h = 199)
  RMSE[i] <- accuracy(fit, ses.btc.test)[2,2]
}

# convert to a data frame and idenitify min alpha value
alpha.fit <- data_frame(alpha, RMSE)
alpha.min <- filter(alpha.fit, RMSE == min(RMSE))

# plot RMSE vs. alpha
ggplot(alpha.fit, aes(alpha, RMSE)) +
  geom_line() +
  geom_point(data = alpha.min, aes(alpha, RMSE), size = 2, color = "blue") +
  labs(title = "RMSE vs Alpha")

ses.btc.opt <- ses(btc.diff, alpha = .01, h = 199)

accuracy(ses.btc.opt, ses.btc.test)

autoplot(ses.btc.opt) +
  theme(legend.position = "bottom") + labs(y = "Price (Differenced)")

autoplot(ses.btc.test) +
  autolayer(ses.btc.opt, alpha = .5) +
  ggtitle("Predicted vs. actuals for the test data set") + 
  labs(y = "Price (Differnced)")

```

```{r}
### Holt's

holt.btc <- holt(btc_train, h = 199)
autoplot(holt.btc) + labs(y = "Price")

holt.btc$model

accuracy(holt.btc, btc_test)

beta <- seq(.0001, .5, by = .001)
RMSE <- NA
for(i in seq_along(beta)) {
  fit <- holt(btc_train, beta = beta[i], h = 199)
  RMSE[i] <- accuracy(fit, btc_test)[2,2]
}

# convert to a data frame and idenitify min alpha value
beta.fit <- data_frame(beta, RMSE)
beta.min <- filter(beta.fit, RMSE == min(RMSE))

# plot RMSE vs. alpha
ggplot(beta.fit, aes(beta, RMSE)) +
  geom_line() +
  geom_point(data = beta.min, aes(beta, RMSE), size = 2, color = "blue") +
  labs(title = "RMSE vs Beta")

holt.btc.opt <- holt(btc_train, h = 199, beta = 0.0151)

accuracy(holt.btc.opt, btc_test)

holt.btc.opt$model

autoplot(holt.btc) +
  ggtitle("Original Holt's Model") + labs(y = "Price")

autoplot(holt.btc.opt) +
  ggtitle("Optimal Holt's Model")  + labs(y = "Price")

```

```{r}
#### Holt Winter's
btc_train <- subset(btc_mthly, end = 53)
btc_test <- subset(btc_mthly, start = 54)

autoplot(decompose(btc_train, type = "additive"))
autoplot(decompose(btc_train, type = "multiplicative"))

btc_hw <- hw(btc_train, seasonal = "additive")
autoplot(forecast(btc_hw)) + labs(y="Price")

btc_hwd <- hw(btc_train, seasonal = "additive", damped = T)
autoplot(forecast(btc_hwd)) + labs(y="Price")

accuracy(btc_hw,btc_test)
accuracy(btc_hwd,btc_test)

```

```{r}
btc_mthly %>% 
  decompose(type="additive") %>%
  autoplot()

tseries::adf.test(btc_mthly, alternative ="stationary")

```

```{r}
lambda <- BoxCox.lambda(btc_mthly)
autoplot(BoxCox(btc_mthly,lambda)) +
  theme_classic() +
  ggtitle("Box-Cox transformed time-series")

btc_mthly_bc <- BoxCox(btc_mthly, lambda)
autoplot(decompose(btc_mthly_bc, type = "additive"))

tseries::adf.test(btc_mthly_bc, alternative = "stationary")

```

```{r}

ndiffs(btc_mthly_bc)
btc_mthly_bc_diff <- diff(btc_mthly_bc, lag = 12)
tseries::adf.test(btc_mthly_bc_diff, alternative = "stationary")
autoplot(btc_mthly_bc_diff) + labs(y = "Price (Differenced",
                                   title = "Series after Seasonal Differentiation")

btc_mthly_bc_diff <- diff(btc_mthly_bc_diff, lag = 1)
autoplot(btc_mthly_bc_diff)
tseries::adf.test(btc_mthly_bc_diff, alternative = "stationary")
Box.test(btc_mthly, type = "Ljung-Box")

#autoplot(decompose(btc_mthly, type = "additive"))
fit <- stl(btc_mthly_bc_diff, s.window = "periodic")
autoplot(fit)

ggAcf(btc_mthly_bc_diff)
ggPacf(btc_mthly_bc_diff)

```

```{r}
auto.arima(btc_mthly_bc_diff, seasonal = F, stepwise = F, approximation = F)

ggtsdisplay(btc_mthly_bc_diff)
fit2 <-arima(btc_mthly_bc_diff, order = c(0,0,1))
checkresiduals(fit2)
adf.test(fit2[["residuals"]], alternative = "stationary")
test1 <- forecast::forecast(fit2, h=13)
autoplot(test1)
accuracy(fit2)

```

